name: Backend CI (Go)

# 1. ¿Cuándo se ejecuta esto? (Triggers)
on:
  push:
    branches: [ "main" ]
    # Solo se ejecuta si hay cambios en la carpeta de Go
    paths:
      - 'backend/**'
      - 'cliente-sidecar/**'
  pull_request:
    branches: [ "main" ]

# 2. ¿Qué trabajos va a realizar?
jobs:
  construir-y-probar:
    # 3. ¿En qué sistema operativo correrá? (GitHub nos presta un Ubuntu)
    runs-on: ubuntu-latest

    # 4. Los pasos secuenciales
    steps:
    - name: 📥 Clonar el repositorio
      uses: actions/checkout@v4

    - name: ⚙️ Instalar Go 1.25
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'
        # Esto habilita el caché para que las dependencias bajen más rápido la próxima vez
        cache-dependency-path: |
          backend/go.sum
          cliente-sidecar/go.sum

    - name: 📦 Verificar Backend (API)
      working-directory: ./backend
      run: |
        go mod tidy
        go build -v ./...

    - name: 👻 Verificar Cliente Sidecar
      working-directory: ./cliente-sidecar
      run: |
        go mod tidy
        go build -v ./...